CREATE OR REPLACE FUNCTION FN_GET_USER_NAME (
    P_USER_ID IN NUMBER
)
RETURN VARCHAR2
AS
    V_FULL_NAME APP_USER.FULL_NAME%TYPE;
BEGIN

SELECT FULL_NAME
INTO V_FULL_NAME
FROM APP_USER
WHERE ID = P_USER_ID;

RETURN V_FULL_NAME;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/