CREATE OR REPLACE VIEW VW_ACTIVE_USER AS
SELECT
    U.ID,
    U.USERNAME,
    U.FULL_NAME,
    U.EMAIL,
    U.DEPT_ID,
    D.DEPT_CODE,
    D.DEPT_NAME,
    U.STATUS,
    U.CREATE_TIME,
    U.UPDATE_TIME
FROM APP_USER U
LEFT JOIN DEPARTMENT D
    ON D.ID = U.DEPT_ID
WHERE U.STATUS = 1;
/
