CREATE OR REPLACE VIEW VW_APP_USER AS
SELECT
    U.ID,
    U.USERNAME,
    U.FULL_NAME,
    U.EMAIL,
    U.STATUS,
    U.DEPT_ID,
    D.DEPT_CODE,
    D.DEPT_NAME,
    U.CREATE_TIME,
    U.UPDATE_TIME
FROM APP_USER U
         LEFT JOIN DEPARTMENT D
                   ON D.ID = U.DEPT_ID;
/