CREATE OR REPLACE PROCEDURE PR_UPDATE_USER_STATUS (
    P_USER_ID IN NUMBER,
    P_STATUS  IN NUMBER
)
AS
BEGIN

    UPDATE APP_USER
    SET STATUS = P_STATUS,
        UPDATE_TIME = SYSTIMESTAMP
    WHERE ID = P_USER_ID;

    DBMS_OUTPUT.PUT_LINE(
        'Updated user ID = ' || P_USER_ID ||
        ', status = ' || P_STATUS
    );

END PR_UPDATE_USER_STATUS;
/
