CREATE OR REPLACE PROCEDURE PR_UPDATE_USER_EMAIL (
    P_USER_ID IN NUMBER,
    P_EMAIL   IN VARCHAR2
)
AS
BEGIN

UPDATE APP_USER
SET
    EMAIL = P_EMAIL,
    UPDATE_TIME = SYSTIMESTAMP
WHERE ID = P_USER_ID;

IF SQL%ROWCOUNT = 0 THEN
        RAISE_APPLICATION_ERROR(
            -20001,
            'USER NOT FOUND: ' || P_USER_ID
        );
END IF;

END;
/