CREATE OR REPLACE PACKAGE PKG_USER AS

    PROCEDURE CREATE_USER (
        P_USERNAME  IN VARCHAR2,
        P_FULL_NAME IN VARCHAR2,
        P_EMAIL     IN VARCHAR2,
        P_DEPT_ID   IN NUMBER,
        P_USER_ID   OUT NUMBER
    );


    PROCEDURE UPDATE_USER (
        P_USER_ID   IN NUMBER,
        P_FULL_NAME IN VARCHAR2,
        P_EMAIL     IN VARCHAR2,
        P_DEPT_ID   IN NUMBER
    );


    PROCEDURE DELETE_USER (
        P_USER_ID IN NUMBER
    );


    FUNCTION GET_USER_NAME (
        P_USER_ID IN NUMBER
    )
    RETURN VARCHAR2;


    FUNCTION COUNT_USER_BY_DEPT (
        P_DEPT_ID IN NUMBER
    )
    RETURN NUMBER;

END PKG_USER;
/