CREATE OR REPLACE PACKAGE BODY PKG_USER AS


    PROCEDURE CREATE_USER (
        P_USERNAME  IN VARCHAR2,
        P_FULL_NAME IN VARCHAR2,
        P_EMAIL     IN VARCHAR2,
        P_DEPT_ID   IN NUMBER,
        P_USER_ID   OUT NUMBER
    )
    AS
BEGIN

        P_USER_ID := SEQ_APP_USER.NEXTVAL;

INSERT INTO APP_USER (
    ID,
    USERNAME,
    FULL_NAME,
    EMAIL,
    DEPT_ID,
    STATUS,
    CREATE_TIME
)
VALUES (
           P_USER_ID,
           P_USERNAME,
           P_FULL_NAME,
           P_EMAIL,
           P_DEPT_ID,
           1,
           SYSTIMESTAMP
       );

END CREATE_USER;



    PROCEDURE UPDATE_USER (
        P_USER_ID   IN NUMBER,
        P_FULL_NAME IN VARCHAR2,
        P_EMAIL     IN VARCHAR2,
        P_DEPT_ID   IN NUMBER
    )
AS
BEGIN

UPDATE APP_USER
SET
    FULL_NAME = P_FULL_NAME,
    EMAIL = P_EMAIL,
    DEPT_ID = P_DEPT_ID,
    UPDATE_TIME = SYSTIMESTAMP
WHERE ID = P_USER_ID;

IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(
                -20002,
                'USER NOT FOUND: ' || P_USER_ID
            );
END IF;

END UPDATE_USER;



    PROCEDURE DELETE_USER (
        P_USER_ID IN NUMBER
    )
AS
BEGIN

UPDATE APP_USER
SET
    STATUS = 0,
    UPDATE_TIME = SYSTIMESTAMP
WHERE ID = P_USER_ID;

END DELETE_USER;



    FUNCTION GET_USER_NAME (
        P_USER_ID IN NUMBER
    )
    RETURN VARCHAR2
    AS
        V_NAME APP_USER.FULL_NAME%TYPE;
BEGIN

SELECT FULL_NAME
INTO V_NAME
FROM APP_USER
WHERE ID = P_USER_ID;

RETURN V_NAME;

EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;

END GET_USER_NAME;



    FUNCTION COUNT_USER_BY_DEPT (
        P_DEPT_ID IN NUMBER
    )
    RETURN NUMBER
    AS
        V_COUNT NUMBER;
BEGIN

SELECT COUNT(*)
INTO V_COUNT
FROM APP_USER
WHERE DEPT_ID = P_DEPT_ID
  AND STATUS = 1;

RETURN V_COUNT;

END COUNT_USER_BY_DEPT;


END PKG_USER;
/